### ISSUE TITLE
Is it possible to support new android 12 58.2.A.0.899

### ISSUE THREAD

**Issue by oit63** [entr0pia/XPatch#1]
just a few days ago, sony relaesed it's 58.2.A.0.899(Android 12), could this project continue to support this version?

**Comment by oit63** [comment]
可能脚本对android12的fstab有点不兼容，我把生产出来的image-new解包，手动删除了system_ext那行，就好了

**Comment by entr0pia** [comment]
在 Linux 上解包 boot.img 后, fstab 所有者为 root, 以普通用户运行的脚本没有权限修改 fstab. 所以用 root 权限运行脚本即可解决.

不过我一直用 Windows 修补镜像 (包括 HK_58.2.A.0.899), 不清楚是不是 Android 12 导致的变化.

![image](https://user-images.githubusercontent.com/30486766/158505265-19d0d3cd-5fb0-4b93-9407-77ffb1f4c4fe.png)
